version: '3.8'
services:
  db:
    image: ghcr.io/stac-utils/pgstac:v0.9.6
    container_name: pgstac-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgstac
    ports:
      - "6005:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 10
  
  migrate:
    image: ghcr.io/stac-utils/stac-fastapi-pgstac:5.0.2
    container_name: pgstac-migrate
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Installing required packages.. .' &&
        pip install pypgstac[psycopg] &&
        echo 'DB is ready. Running pypgstac migrate...' &&
        pypgstac migrate --dsn postgresql://postgres:pgpass@db:5432/pgstac --toversion 0.9.6
      "
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=pgpass
      - POSTGRES_DBNAME=pgstac
      - POSTGRES_HOST=pgstac-db
      - POSTGRES_PORT=5432
  stac-api:
    image: ghcr.io/stac-utils/stac-fastapi-pgstac:5.0.2
    container_name: stac-fastapi
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - ROOT_PATH=/stac/api
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - ENVIRONMENT=production
      - POSTGRES_HOST_READER=pgstac-db
      - POSTGRES_HOST_WRITER=pgstac-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=pgpass
      - POSTGRES_DBNAME=pgstac
      - ENABLED_EXTENSIONS=filter,transactions,sort,query
    ports:
      - "6006:8080"
  
  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    container_name: stac-loader
    restart: unless-stopped 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${EXTERNAL_CATALOG_LOCATION_DIRECTORY:-/media/servers/STAC/current_stac_catalog}:/app/stac_catalog
      - ./output:/app/output
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=pgpass
      - POSTGRES_DB=pgstac
      - CATALOG_PATH=/app/stac_catalog/catalog.json
      - COLLECTIONS_OUTPUT_FILE=/app/output/collections.json
      - ITEMS_OUTPUT_FILE=/app/output/items.json
volumes:
  pgdata: